apiVersion: v1
kind: Service
metadata:
  name: nest-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: nest-load-balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
